customer_transactions_dw:
  target: prod
  outputs:
    prod:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('WAREHOUSE_DB') }}"
      schema: "{{ env_var('WAREHOUSE_DB') }}"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public
      
    dev:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('WAREHOUSE_DB') }}"
      schema: "{{ env_var('WAREHOUSE_DB') }}"
      threads: 2
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public
