version: 2

models:
  # ===========================================================================
  # DIMENSION TABLES
  # ===========================================================================
  
  - name: dim_customers
    description: |
      Customer dimension table with aggregated metrics and segmentation.
      Includes unknown customers (customer_id = -1) for transactions without customer assignment.
    
    meta:
      owner: "data-platform-team"
      layer: "mart"
      refresh_frequency: "daily"
    
    tests:
      - dbt_utils.expression_is_true:
          expression: "customer_id >= -1"
          config:
            severity: error
    
    columns:
      - name: customer_id
        description: Customer unique identifier (-1 for unknown customers)
        tests:
          - unique
          - not_null
      
      - name: customer_name
        description: Customer display name
        tests:
          - not_null
      
      - name: total_transactions
        description: Total number of transactions by this customer
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 1"
      
      - name: total_revenue
        description: Total revenue generated by this customer
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: customer_value_segment
        description: Customer segmentation by total revenue
        tests:
          - accepted_values:
              values: ['High Value', 'Medium Value', 'Low Value']
      
      - name: customer_tier
        description: Customer tier based on average transaction value
        tests:
          - accepted_values:
              values: ['Premium', 'Standard', 'Budget']
      
      - name: customer_status
        description: Customer activity status based on recency
        tests:
          - accepted_values:
              values: ['Active', 'At Risk', 'Inactive']
  
  # ---------------------------------------------------------------------------
  
  - name: dim_products
    description: |
      Product dimension table with aggregated sales metrics and performance indicators.
      Includes derived attributes like product category and performance segments.
    
    meta:
      owner: "data-platform-team"
      layer: "mart"
      refresh_frequency: "daily"
    
    tests:
      - dbt_utils.expression_is_true:
          expression: "total_transactions >= 1"
    
    columns:
      - name: product_id
        description: Product unique identifier
        tests:
          - unique
          - not_null
      
      - name: product_name
        description: Product name
        tests:
          - not_null
          - accepted_values:
              values: ['Product A', 'Product B', 'Product C', 'Product D', 'Product E']
      
      - name: product_category
        description: Product category (derived from name)
        tests:
          - not_null
          - accepted_values:
              values: ['Category 1', 'Category 2', 'Category 3']
      
      - name: total_revenue
        description: Total revenue generated by this product
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      
      - name: avg_price
        description: Average unit price
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
      
      - name: performance_segment
        description: Product performance classification
        tests:
          - accepted_values:
              values: ['Top Performer', 'Good Performer', 'Low Performer']
  
  # ---------------------------------------------------------------------------
  
  - name: dim_dates
    description: |
      Date dimension with pre-calculated date attributes and flags.
      Enables efficient time-based analysis without runtime date calculations.
    
    meta:
      owner: "data-platform-team"
      layer: "mart"
      refresh_frequency: "daily"
    
    columns:
      - name: date_day
        description: Calendar date (primary key)
        tests:
          - unique
          - not_null
      
      - name: year
        description: Year (e.g., 2023)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2020
              max_value: 2030
      
      - name: month
        description: Month number (1-12)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
      
      - name: quarter
        description: Quarter number (1-4)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 4
      
      - name: day_of_week
        description: Day of week (0=Sunday, 6=Saturday)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 6
      
      - name: is_weekend
        description: Flag indicating weekend day
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      
      - name: is_weekday
        description: Flag indicating weekday
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
  
  # ===========================================================================
  # FACT TABLES
  # ===========================================================================
  
  - name: fact_transactions
    description: |
      Transaction fact table with foreign keys to dimension tables.
      Grain: One row per transaction.
      Includes measures, flags, and data quality indicators.
    
    meta:
      owner: "data-platform-team"
      layer: "mart"
      refresh_frequency: "daily"
    
    tests:
      - dbt_utils.expression_is_true:
          expression: "line_total >= 0"
          config:
            severity: warn
    
    columns:
      - name: transaction_id
        description: Transaction unique identifier (primary key)
        tests:
          - unique
          - not_null
      
      - name: customer_key
        description: Foreign key to dim_customers
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      
      - name: product_key
        description: Foreign key to dim_products
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      
      - name: date_key
        description: Foreign key to dim_dates
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_day
      
      - name: quantity
        description: Quantity purchased
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      
      - name: unit_price
        description: Price per unit
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
      
      - name: line_total
        description: Total transaction amount (subtotal + tax)
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= line_subtotal"
              where: "line_subtotal IS NOT NULL"
      
      - name: data_quality_score
        description: Data quality score (0-5, where 5 is perfect)
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5
      
      - name: is_clean_record
        description: Flag indicating no data quality issues
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
  
  # ===========================================================================
  # AGGREGATE TABLES
  # ===========================================================================
  
  - name: monthly_customer_summary
    description: |
      Monthly customer summary with aggregated metrics.
      Grain: One row per customer per month.
      Enables fast month-over-month analysis.
    
    meta:
      owner: "data-platform-team"
      layer: "mart"
      refresh_frequency: "daily"
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_key
            - year_month
    
    columns:
      - name: customer_key
        description: Customer identifier
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      
      - name: year_month
        description: Year-month (YYYY-MM format)
        tests:
          - not_null
      
      - name: transaction_count
        description: Number of transactions in the month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 1"
      
      - name: total_revenue
        description: Total revenue in the month
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: monthly_performance_tier
        description: Performance classification for the month
        tests:
          - not_null
          - accepted_values:
              values: ['High Performer', 'Medium Performer', 'Low Performer']
  
  # ---------------------------------------------------------------------------
  
  - name: product_performance
    description: |
      Daily product performance metrics with rolling averages.
      Grain: One row per product per day.
      Supports trend analysis and ranking.
    
    meta:
      owner: "data-platform-team"
      layer: "mart"
      refresh_frequency: "daily"
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_key
            - date_key
    
    columns:
      - name: product_key
        description: Product identifier
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      
      - name: date_key
        description: Date
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_day
      
      - name: total_revenue
        description: Total revenue for the day
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: daily_revenue_rank
        description: Product rank by revenue for the day
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 1"
      
      - name: trend_indicator
        description: Revenue trend compared to 7-day average
        tests:
          - not_null
          - accepted_values:
              values: ['Above Trend', 'On Trend', 'Below Trend']
      
      - name: daily_performance_tier
        description: Performance tier for the day
        tests:
          - not_null
          - accepted_values:
              values: ['Top Performer', 'Good Performer', 'Standard Performer']
